--------------------------------------------------------
--  File created - środa-listopada-19-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for DB Link FILIA1_LINK
--------------------------------------------------------

  CREATE DATABASE LINK "FILIA1_LINK"
   USING 'FILIA1_PDB';
--------------------------------------------------------
--  DDL for Sequence CZYTELNICY_SEQ_F2
--------------------------------------------------------

   CREATE SEQUENCE  "BIBLIOTEKA"."CZYTELNICY_SEQ_F2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5020 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KSIAZKI_SEQ_F2
--------------------------------------------------------

   CREATE SEQUENCE  "BIBLIOTEKA"."KSIAZKI_SEQ_F2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5020 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REZERWACJE_SEQ_F2
--------------------------------------------------------

   CREATE SEQUENCE  "BIBLIOTEKA"."REZERWACJE_SEQ_F2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5020 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence WYPOZYCZENIA_SEQ_F2
--------------------------------------------------------

   CREATE SEQUENCE  "BIBLIOTEKA"."WYPOZYCZENIA_SEQ_F2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5040 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUTORZY
--------------------------------------------------------

  CREATE TABLE "BIBLIOTEKA"."AUTORZY" 
   (	"ID_AUTORA" NUMBER(10,0), 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CZYTELNICY
--------------------------------------------------------

  CREATE TABLE "BIBLIOTEKA"."CZYTELNICY" 
   (	"ID_CZYTELNIKA" NUMBER(10,0), 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(100 BYTE), 
	"ADRES" VARCHAR2(200 BYTE), 
	"TELEFON" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ID_FILII" NUMBER(2,0), 
	"LICZBA_WYPOZYCZONYCH" NUMBER(2,0) DEFAULT 0, 
	"LIMIT_WYPOZYCZEN" NUMBER(2,0) DEFAULT 5, 
	"HASLO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FILIE
--------------------------------------------------------

  CREATE TABLE "BIBLIOTEKA"."FILIE" 
   (	"ID_FILII" NUMBER(2,0), 
	"NAZWA" VARCHAR2(100 BYTE), 
	"ADRES" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KSIAZKI
--------------------------------------------------------

  CREATE TABLE "BIBLIOTEKA"."KSIAZKI" 
   (	"ID_KSIAZKI" NUMBER(10,0), 
	"TYTUL" VARCHAR2(200 BYTE), 
	"ROK_WYDANIA" NUMBER(4,0), 
	"ID_AUTORA" NUMBER(10,0), 
	"ID_FILII" NUMBER(2,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'dostępna'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "BIBLIOTEKA"."REZERWACJE" 
   (	"ID_REZERWACJI" NUMBER(10,0), 
	"ID_KSIAZKI" NUMBER(10,0), 
	"ID_CZYTELNIKA" NUMBER(10,0), 
	"DATA_REZERWACJI" DATE DEFAULT SYSDATE, 
	"WAZNOSC_DO" DATE DEFAULT SYSDATE + 3, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'aktywna', 
	"ID_FILII_KSIAZKI" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WYPOZYCZENIA
--------------------------------------------------------

  CREATE TABLE "BIBLIOTEKA"."WYPOZYCZENIA" 
   (	"ID_WYPOZYCZENIA" NUMBER(10,0), 
	"ID_KSIAZKI" NUMBER(10,0), 
	"ID_CZYTELNIKA" NUMBER(10,0), 
	"DATA_WYPOZYCZENIA" DATE DEFAULT SYSDATE, 
	"DATA_PLAN_ZWROTU" DATE, 
	"DATA_ZWROTU" DATE, 
	"ID_FILII_KSIAZKI" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View CZYTELNICY_CALOSC
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BIBLIOTEKA"."CZYTELNICY_CALOSC" ("ID_CZYTELNIKA", "IMIE", "NAZWISKO", "ADRES", "TELEFON", "EMAIL", "ID_FILII", "LICZBA_WYPOZYCZONYCH", "LIMIT_WYPOZYCZEN", "HASLO") AS 
  SELECT "ID_CZYTELNIKA","IMIE","NAZWISKO","ADRES","TELEFON","EMAIL","ID_FILII","LICZBA_WYPOZYCZONYCH","LIMIT_WYPOZYCZEN","HASLO" FROM CZYTELNICY -- Lokalne dane z Filii 2
UNION ALL
SELECT "ID_CZYTELNIKA","IMIE","NAZWISKO","ADRES","TELEFON","EMAIL","ID_FILII","LICZBA_WYPOZYCZONYCH","LIMIT_WYPOZYCZEN","HASLO" FROM CZYTELNICY@filia1_link
;
--------------------------------------------------------
--  DDL for View KSIAZKI_CALOSC
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BIBLIOTEKA"."KSIAZKI_CALOSC" ("ID_KSIAZKI", "TYTUL", "ROK_WYDANIA", "ID_AUTORA", "ID_FILII", "STATUS") AS 
  SELECT "ID_KSIAZKI","TYTUL","ROK_WYDANIA","ID_AUTORA","ID_FILII","STATUS" FROM KSIAZKI -- Lokalne dane z Filii 2
UNION ALL
SELECT "ID_KSIAZKI","TYTUL","ROK_WYDANIA","ID_AUTORA","ID_FILII","STATUS" FROM KSIAZKI@filia1_link
;
--------------------------------------------------------
--  DDL for View REZERWACJE_CALOSC
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BIBLIOTEKA"."REZERWACJE_CALOSC" ("ID_REZERWACJI", "ID_KSIAZKI", "ID_CZYTELNIKA", "DATA_REZERWACJI", "WAZNOSC_DO", "STATUS", "ID_FILII_KSIAZKI") AS 
  SELECT "ID_REZERWACJI","ID_KSIAZKI","ID_CZYTELNIKA","DATA_REZERWACJI","WAZNOSC_DO","STATUS","ID_FILII_KSIAZKI" FROM REZERWACJE 
UNION ALL
SELECT "ID_REZERWACJI","ID_KSIAZKI","ID_CZYTELNIKA","DATA_REZERWACJI","WAZNOSC_DO","STATUS","ID_FILII_KSIAZKI" FROM REZERWACJE@filia1_link
;
--------------------------------------------------------
--  DDL for View V_AKTUALNE_WYPOZYCZENIA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BIBLIOTEKA"."V_AKTUALNE_WYPOZYCZENIA" ("ID_WYPOZYCZENIA", "DATA_WYPOZYCZENIA", "DATA_PLAN_ZWROTU", "ID_KSIAZKI", "ID_CZYTELNIKA", "TYTUL", "AUTOR", "CZYTELNIK", "TELEFON_CZYTELNIKA", "FILIA_KSIAZKI", "FILIA_CZYTELNIKA") AS 
  SELECT 
    w.id_wypozyczenia,
    w.data_wypozyczenia,
    w.data_plan_zwrotu,
    
    -- DODAJEMY TE DWA KLUCZOWE POLA:
    w.id_ksiazki,
    w.id_czytelnika,
    
    k.tytul,
    a.imie || ' ' || a.nazwisko AS autor,
    c.imie || ' ' || c.nazwisko AS czytelnik,
    c.telefon AS telefon_czytelnika,
    f_ksiazki.nazwa AS filia_ksiazki,
    f_czytelnika.nazwa AS filia_czytelnika
FROM 
    WYPOZYCZENIA_CALOSC w
JOIN 
    KSIAZKI_CALOSC k ON w.id_ksiazki = k.id_ksiazki
JOIN 
    CZYTELNICY_CALOSC c ON w.id_czytelnika = c.id_czytelnika
JOIN 
    AUTORZY a ON k.id_autora = a.id_autora
JOIN
    FILIE f_ksiazki ON k.id_filii = f_ksiazki.id_filii
JOIN
    FILIE f_czytelnika ON c.id_filii = f_czytelnika.id_filii
WHERE 
    w.data_zwrotu IS NULL
;
--------------------------------------------------------
--  DDL for View WYPOZYCZENIA_CALOSC
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BIBLIOTEKA"."WYPOZYCZENIA_CALOSC" ("ID_WYPOZYCZENIA", "ID_KSIAZKI", "ID_CZYTELNIKA", "DATA_WYPOZYCZENIA", "DATA_PLAN_ZWROTU", "DATA_ZWROTU", "ID_FILII_KSIAZKI") AS 
  SELECT "ID_WYPOZYCZENIA","ID_KSIAZKI","ID_CZYTELNIKA","DATA_WYPOZYCZENIA","DATA_PLAN_ZWROTU","DATA_ZWROTU","ID_FILII_KSIAZKI" FROM WYPOZYCZENIA
UNION ALL
SELECT "ID_WYPOZYCZENIA","ID_KSIAZKI","ID_CZYTELNIKA","DATA_WYPOZYCZENIA","DATA_PLAN_ZWROTU","DATA_ZWROTU","ID_FILII_KSIAZKI" FROM WYPOZYCZENIA@filia1_link
;
REM INSERTING into BIBLIOTEKA.AUTORZY
SET DEFINE OFF;
Insert into BIBLIOTEKA.AUTORZY (ID_AUTORA,IMIE,NAZWISKO) values ('200','Jan','Kochanowski');
Insert into BIBLIOTEKA.AUTORZY (ID_AUTORA,IMIE,NAZWISKO) values ('101','Adam','Mickiewicz');
Insert into BIBLIOTEKA.AUTORZY (ID_AUTORA,IMIE,NAZWISKO) values ('102','Henryk','Sienkiewicz');
Insert into BIBLIOTEKA.AUTORZY (ID_AUTORA,IMIE,NAZWISKO) values ('103','Olga','Tokarczuk');
Insert into BIBLIOTEKA.AUTORZY (ID_AUTORA,IMIE,NAZWISKO) values ('220','J.K.','Rowling');
REM INSERTING into BIBLIOTEKA.CZYTELNICY
SET DEFINE OFF;
Insert into BIBLIOTEKA.CZYTELNICY (ID_CZYTELNIKA,IMIE,NAZWISKO,ADRES,TELEFON,EMAIL,ID_FILII,LICZBA_WYPOZYCZONYCH,LIMIT_WYPOZYCZEN,HASLO) values ('501','Jan','Kowalski',null,null,null,'2','0','5',null);
Insert into BIBLIOTEKA.CZYTELNICY (ID_CZYTELNIKA,IMIE,NAZWISKO,ADRES,TELEFON,EMAIL,ID_FILII,LICZBA_WYPOZYCZONYCH,LIMIT_WYPOZYCZEN,HASLO) values ('502','Ewa','Zielińska',null,null,null,'2','0','5',null);
Insert into BIBLIOTEKA.CZYTELNICY (ID_CZYTELNIKA,IMIE,NAZWISKO,ADRES,TELEFON,EMAIL,ID_FILII,LICZBA_WYPOZYCZONYCH,LIMIT_WYPOZYCZEN,HASLO) values ('5000','Mariusz','Gąsiewicz',null,null,'mariusz.gasiewicz1400@gmail.com','2','0','5','$2b$12$M8RnN8yB4HqDDebRxwQ40eSOtQ/oSRjOH9jNHhM0KLWvLE2Opd2W6');
REM INSERTING into BIBLIOTEKA.FILIE
SET DEFINE OFF;
Insert into BIBLIOTEKA.FILIE (ID_FILII,NAZWA,ADRES) values ('1','Filia Centrum','ul. Centralna 1, Warszawa');
Insert into BIBLIOTEKA.FILIE (ID_FILII,NAZWA,ADRES) values ('2','Filia Krzyki','ul. Kwiatowa 5, Warszawa');
REM INSERTING into BIBLIOTEKA.KSIAZKI
SET DEFINE OFF;
Insert into BIBLIOTEKA.KSIAZKI (ID_KSIAZKI,TYTUL,ROK_WYDANIA,ID_AUTORA,ID_FILII,STATUS) values ('2001','Potop','1886','102','2','dostępna');
Insert into BIBLIOTEKA.KSIAZKI (ID_KSIAZKI,TYTUL,ROK_WYDANIA,ID_AUTORA,ID_FILII,STATUS) values ('2002','Ogniem i Mieczem','1884','102','2','dostępna');
Insert into BIBLIOTEKA.KSIAZKI (ID_KSIAZKI,TYTUL,ROK_WYDANIA,ID_AUTORA,ID_FILII,STATUS) values ('5000','Harry Potter - Kamień Filozoficzny','2022','220','2','dostępna');
REM INSERTING into BIBLIOTEKA.REZERWACJE
SET DEFINE OFF;
Insert into BIBLIOTEKA.REZERWACJE (ID_REZERWACJI,ID_KSIAZKI,ID_CZYTELNIKA,DATA_REZERWACJI,WAZNOSC_DO,STATUS,ID_FILII_KSIAZKI) values ('5000','2002','100',to_date('25/11/18','RR/MM/DD'),to_date('25/11/21','RR/MM/DD'),'zrealizowana','2');
Insert into BIBLIOTEKA.REZERWACJE (ID_REZERWACJI,ID_KSIAZKI,ID_CZYTELNIKA,DATA_REZERWACJI,WAZNOSC_DO,STATUS,ID_FILII_KSIAZKI) values ('5001','2002','100',to_date('25/11/18','RR/MM/DD'),to_date('25/11/21','RR/MM/DD'),'zrealizowana','2');
REM INSERTING into BIBLIOTEKA.WYPOZYCZENIA
SET DEFINE OFF;
Insert into BIBLIOTEKA.WYPOZYCZENIA (ID_WYPOZYCZENIA,ID_KSIAZKI,ID_CZYTELNIKA,DATA_WYPOZYCZENIA,DATA_PLAN_ZWROTU,DATA_ZWROTU,ID_FILII_KSIAZKI) values ('5000','2001','501',to_date('25/11/18','RR/MM/DD'),to_date('25/12/10','RR/MM/DD'),to_date('25/11/18','RR/MM/DD'),'2');
Insert into BIBLIOTEKA.WYPOZYCZENIA (ID_WYPOZYCZENIA,ID_KSIAZKI,ID_CZYTELNIKA,DATA_WYPOZYCZENIA,DATA_PLAN_ZWROTU,DATA_ZWROTU,ID_FILII_KSIAZKI) values ('5020','2002','100',to_date('25/11/18','RR/MM/DD'),to_date('25/12/18','RR/MM/DD'),to_date('25/11/18','RR/MM/DD'),'2');
Insert into BIBLIOTEKA.WYPOZYCZENIA (ID_WYPOZYCZENIA,ID_KSIAZKI,ID_CZYTELNIKA,DATA_WYPOZYCZENIA,DATA_PLAN_ZWROTU,DATA_ZWROTU,ID_FILII_KSIAZKI) values ('5001','2002','100',to_date('25/11/18','RR/MM/DD'),to_date('25/12/18','RR/MM/DD'),to_date('25/11/18','RR/MM/DD'),'2');
Insert into BIBLIOTEKA.WYPOZYCZENIA (ID_WYPOZYCZENIA,ID_KSIAZKI,ID_CZYTELNIKA,DATA_WYPOZYCZENIA,DATA_PLAN_ZWROTU,DATA_ZWROTU,ID_FILII_KSIAZKI) values ('5021','2002','501',to_date('25/11/18','RR/MM/DD'),to_date('25/12/18','RR/MM/DD'),to_date('25/11/18','RR/MM/DD'),'2');
--------------------------------------------------------
--  DDL for Synonymn CZYTELNICY_F1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "BIBLIOTEKA"."CZYTELNICY_F1" FOR "CZYTELNICY"@"FILIA1_LINK";
--------------------------------------------------------
--  DDL for Synonymn KSIAZKI_F1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "BIBLIOTEKA"."KSIAZKI_F1" FOR "KSIAZKI"@"FILIA1_LINK";
--------------------------------------------------------
--  Constraints for Table AUTORZY
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."AUTORZY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."AUTORZY" ADD PRIMARY KEY ("ID_AUTORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WYPOZYCZENIA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."WYPOZYCZENIA" MODIFY ("ID_KSIAZKI" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."WYPOZYCZENIA" MODIFY ("ID_CZYTELNIKA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."WYPOZYCZENIA" MODIFY ("ID_FILII_KSIAZKI" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."WYPOZYCZENIA" ADD CONSTRAINT "CHK_WYP_FILIA_2" CHECK (id_filii_ksiazki = 2) ENABLE;
  ALTER TABLE "BIBLIOTEKA"."WYPOZYCZENIA" ADD PRIMARY KEY ("ID_WYPOZYCZENIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FILIE
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."FILIE" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."FILIE" MODIFY ("ADRES" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."FILIE" ADD PRIMARY KEY ("ID_FILII")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CZYTELNICY
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."CZYTELNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."CZYTELNICY" MODIFY ("ID_FILII" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."CZYTELNICY" ADD CONSTRAINT "CHK_FILIA_2" CHECK (id_filii = 2) ENABLE;
  ALTER TABLE "BIBLIOTEKA"."CZYTELNICY" ADD PRIMARY KEY ("ID_CZYTELNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."REZERWACJE" MODIFY ("ID_KSIAZKI" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."REZERWACJE" MODIFY ("ID_CZYTELNIKA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."REZERWACJE" MODIFY ("ID_FILII_KSIAZKI" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."REZERWACJE" ADD CONSTRAINT "CHK_REZ_FILIA_2" CHECK (id_filii_ksiazki = 2) ENABLE;
  ALTER TABLE "BIBLIOTEKA"."REZERWACJE" ADD PRIMARY KEY ("ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KSIAZKI
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" MODIFY ("TYTUL" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" MODIFY ("ID_FILII" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" ADD CONSTRAINT "CHK_KSIAZKI_STATUS_V2" CHECK (status IN ('dostępna', 'wypożyczona', 'zarezerwowana')) ENABLE;
  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" ADD CONSTRAINT "CHK_KSIAZKI_FILIA_2" CHECK (id_filii = 2) ENABLE;
  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" ADD PRIMARY KEY ("ID_KSIAZKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CZYTELNICY
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."CZYTELNICY" ADD CONSTRAINT "FK_CZYTELNICY_FILIE" FOREIGN KEY ("ID_FILII")
	  REFERENCES "BIBLIOTEKA"."FILIE" ("ID_FILII") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KSIAZKI
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" ADD CONSTRAINT "FK_KSIAZKI_AUTORZY_F2" FOREIGN KEY ("ID_AUTORA")
	  REFERENCES "BIBLIOTEKA"."AUTORZY" ("ID_AUTORA") ENABLE;
  ALTER TABLE "BIBLIOTEKA"."KSIAZKI" ADD CONSTRAINT "FK_KSIAZKI_FILIE_F2" FOREIGN KEY ("ID_FILII")
	  REFERENCES "BIBLIOTEKA"."FILIE" ("ID_FILII") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."REZERWACJE" ADD CONSTRAINT "FK_REZ_KSIAZKI_F2" FOREIGN KEY ("ID_KSIAZKI")
	  REFERENCES "BIBLIOTEKA"."KSIAZKI" ("ID_KSIAZKI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WYPOZYCZENIA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTEKA"."WYPOZYCZENIA" ADD CONSTRAINT "FK_WYP_KSIAZKI_F2" FOREIGN KEY ("ID_KSIAZKI")
	  REFERENCES "BIBLIOTEKA"."KSIAZKI" ("ID_KSIAZKI") ENABLE;
